version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DOCKER_MYSQL_URL: mysql://root:rootpassword@mysql_db:3306/free_illustrations_db
    networks:
      - frontend
      - backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./server:/app

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mysql_data: