name: CI Pipeline

on:
  push:
    branches:
      - "*"   # Trigger on every push
  pull_request:
    branches:
      - main   # Trigger on pull request targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the operating system for the runner

    steps: # Action needed by github actions to read the code
    - name: Checkout code
      uses: actions/checkout@v3

      # Runs the docker-compose  
    - name: Run Docker Compose for services
      run: |
        docker-compose -f docker-compose.yml up -d --build

      # Runs all tests  
#    - name: Run tests
#      run: |
#        docker-compose exec server npm test 
#        docker-compose exec client npm test 

      # Runs the linting script, that only fails on errors
    - name: Run linting for client
      run: |
        docker-compose exec client npm run pipeline-lint  

      # Shuts down the services and all volumes associated
    - name: Shut down Docker Compose services
      run: |
        docker-compose down -v

